# -*- coding: utf-8 -*-
"""RS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15b9XcPulYQKEqTyz8VOo0GVre5i_TOzn
"""

# ---------------------------------------
# Crop Disease Detection + Yield Prediction
# Using RS-A1_yield.csv dataset
# ---------------------------------------

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from keras.preprocessing.image import img_to_array
import random

# Step 1: Load Dataset
# ---------------------------------------
df = pd.read_csv('/content/RS-A1_yield.csv')

# Select useful columns for yield prediction
# Target: hg/ha_yield
# Features: average_rain_fall_mm_per_year, pesticides_tonnes, avg_temp
df = df.dropna()

X = df[['average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']]
y = df['hg/ha_yield']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Random Forest Model for Yield Prediction
# ---------------------------------------
yield_model = RandomForestRegressor(n_estimators=100, random_state=42)
yield_model.fit(X_train, y_train)

# Evaluate model
y_pred = yield_model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print(f"Random Forest R² Score: {r2:.3f}")
print(f"Mean Squared Error: {mse:.2f}")

# Step 3: Simple CNN for Disease Detection (Placeholder Example)
# ---------------------------------------
# Random sample images since your dataset doesn't have image data yet
X_train_images = np.random.rand(100, 64, 64, 3)
y_train_images = np.random.randint(2, size=100)  # 0=Healthy, 1=Diseased

cnn_model = Sequential([
    Conv2D(32, (3, 3), input_shape=(64, 64, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])

cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
cnn_model.fit(X_train_images, y_train_images, epochs=3, batch_size=10, verbose=1)

# Step 4: Recommendation System
# ---------------------------------------
def recommend(disease_prediction, yield_prediction):
    if disease_prediction >= 0.5:
        return "⚠️ Disease detected! Recommended: Apply pesticide."
    elif yield_prediction < 30000:
        return "🌾 Low yield predicted! Recommended: Improve irrigation and soil quality."
    else:
        return "✅ Crop is healthy and yield prediction is optimal."

# Step 5: Test the System with Sample Input
# ---------------------------------------
# Mock test image (replace with actual image later)
test_image = np.random.rand(1, 64, 64, 3)
disease_prediction = cnn_model.predict(test_image)[0][0]

# Use a real test row from dataset for environmental prediction
test_env_data = np.array([[1500, 120, 16]])  # rainfall, pesticides, temp
yield_prediction = yield_model.predict(test_env_data)[0]

# Get recommendation
recommendation = recommend(disease_prediction, yield_prediction)

# Step 6: Display Results
# ---------------------------------------
print(f"\nDisease Prediction: {disease_prediction:.4f} (0: Healthy, 1: Diseased)")
print(f"Yield Prediction: {yield_prediction:.2f} hg/ha")
print(f"Recommendation: {recommendation}")