# -*- coding: utf-8 -*-
"""RS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxKEoIqmk7TAXgDAa0hOdZ1d2NpNbcw8
"""

# ------------------------------------------------------------
# Movie Recommendation System using RS-A2_A3_movie & RS-A2_A3_tag
# ------------------------------------------------------------

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# Step 1: Load Datasets
# ------------------------------------------------------------
movies_df = pd.read_csv('/content/RS-A2_A3_movie.csv')
tags_df = pd.read_csv('/content/RS-A2_A3_tag.csv')

# Display sample
print("🎬 Movies Data:")
print(movies_df.head())
print("\n🏷️ Tags Data:")
print(tags_df.head())

# Step 2: Merge datasets on 'movieId'
# ------------------------------------------------------------
merged_df = pd.merge(movies_df, tags_df, on='movieId', how='left')

# Combine genres and tags into one column for textual content
merged_df['combined'] = merged_df['genres'].fillna('') + ' ' + merged_df['tag'].fillna('')

# Drop duplicates (some movies appear multiple times due to different tags)
merged_df = merged_df.groupby(['movieId', 'title'])['combined'].apply(lambda x: ' '.join(x)).reset_index()

# Step 3: TF-IDF Vectorization
# ------------------------------------------------------------
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(merged_df['combined'])

# Compute cosine similarity
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Step 4: Build Recommendation Function
# ------------------------------------------------------------
indices = pd.Series(merged_df.index, index=merged_df['title']).drop_duplicates()

def get_recommendations(title, cosine_sim=cosine_sim):
    if title not in indices:
        return f"❌ Movie '{title}' not found in dataset."

    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Top 5 similar movies (excluding itself)
    sim_scores = sim_scores[1:6]
    movie_indices = [i[0] for i in sim_scores]

    return merged_df[['title']].iloc[movie_indices]

# Step 5: Interactive Input
# ------------------------------------------------------------
print("\n🎥 Enter a movie title to get recommendations:")
user_input = input("Movie Title: ")

recommendations = get_recommendations(user_input)

print("\n---------------- Recommendations ----------------")
print(recommendations)
print("-------------------------------------------------")